#!/usr/bin/env bash

set -e
echo "-----------------------------"
echo "| Running Pre-Commit Checks |"
echo "| Running Code Quality      |"
echo "-----------------------------"
sh -c "pnpm lint:check"
sh -c "pnpm format:check"
sh -c "pnpm type:check"

echo "-----------------------------"
echo "| Running Test Cases        |"
echo "-----------------------------"
sh -c "pnpm test --silent"

